### ISSUE TITLE
Iterations annotation

### ISSUE THREAD

**Issue by Bijnagte** [Bijnagte/spock-genesis#13]
Create an annotation that can cause the spec to run the specified number of iterations. This should most likely be implemented as an AST transformation during the Canonicalization phase (after Semantic Analysis). Spock does it's work during Semantic Analysis so the methods that return the data providers in the where block are present in the AST at that point. We can hook in to the data provider methods and augment the producers to run the desired number of Iterations. I looked at using extensions but there is no good way to hook into the data providers without weird hacks like using a thread local as a flag or asking for (and implementing) a hook for data providers in the spock runtime.

**Comment by mariogarcia** [comment]
Good idea, I guess it makes sense to think it could be applied to a whole `Specification` and maybe sometimes override it for a single `feature`. Something like this:

```
import spock.genesis.Gen
import spock.lang.Specification

@Gen.Times(100)
class MySpec extends Specification {

    def 'check commutative'() {
         expect: 'commutative property to hold'
             a + b == b + a
         where: 'possible values are'
             [a, b] << Gen.tuple(Gen.integer, Gen.integer)
    }

    @Gen.Times(50)
    def 'check associative'() {
         expect: 'commutative property to hold'
             a + ( b + c ) == (a + b) + c
         where: 'possible values are'
             [a, b, c] << Gen.tuple(Gen.integer, Gen.integer, Gen.integer)
    }
}
```

So if I'm not wrong, what you're saying is that if I annotated my feature like this:

```
    @Gen.Times(50)
    def 'check associative'() {
         expect: 'commutative property to hold'
             a + ( b + c ) == (a + b) + c
         where: 'possible values are'
             [a, b, c] << Gen.tuple(Gen.integer, Gen.integer, Gen.integer)
    }
```

underneath this should be translated to:

```
    def 'check associative'() {
         expect: 'commutative property to hold'
             a + ( b + c ) == (a + b) + c
         where: 'possible values are'
             [a, b, c] << Gen.tuple(Gen.integer, Gen.integer, Gen.integer).take(50)
    }
```

Is that the idea ?

**Comment by Bijnagte** [comment]
Yes that is the general idea but I was thinking of implementing it by wrapping the data provider in a new generator.
So it would be more like this:

``` groovy
@Gen.Times(50)
 def 'check associative'() {
         expect: 'commutative property to hold'
             a + ( b + c ) == (a + b) + c
         where: 'possible values are'
             [a, b, c] << new LimitedGenerator(Gen.tuple(Gen.integer, Gen.integer, Gen.integer), 50)
    }
```

That would also enable using multiple data providers without needing to coordinate their length

``` groovy
 def 'check associative'() {
         expect: 'commutative property to hold'
             a + ( b + c ) == (a + b) + c
         where: 'possible values are'
             a << Gen.integer
             b << Gen.integer
             c << Gen.integer
    }
```

It may even be desirable to wrap non-generator based providers, potentially making them cycle

``` groovy
@Gen.Times(value= 50, cycle=true)
 def 'check associative'() {
         expect: 'commutative property to hold'
             a + ( b + c ) == (a + b) + c
         where: 'possible values are'
             a << [1, 2, 3]
             b << Gen.integer
             c << Gen.integer
   }
```

Would turn into

``` groovy
@Gen.Times(value= 50, cycle=true)
 def 'check associative'() {
         expect: 'commutative property to hold'
             a + ( b + c ) == (a + b) + c
         where: 'possible values are'
             a << new LimitedGenerator(new CyclicGenerator([1, 2, 3]), 50)
             b << new LimitedGenerator(Gen.integer, 50)
             c << new LimitedGenerator(Gen.integer, 50)
   }
```

**Comment by mariogarcia** [comment]
I've started a possible implementation. Guidelines I'm following:
- Only changing expressions in the where block
- First deal with cases where the type is given by the compiler: lists, ranges, arrays. Those are easy ones.
- Then dealing with method calls, meaning. Methods returning objects eligible to be used in generators.

About this last case, there could be cases where the compiler is not gonna help if the method return type is `def`. Throwing a compilation error seems a reasonable solution

What do you think ?

Mario

**Comment by mariogarcia** [comment]
`UPDATE`:
- Detection of `datapipes` (LHS << RHS) in the `where` block works ok.
- I'm already capable of creating a `LimitedGenerator` from `list` and `ranges`. 
- I'm leaving generators use cases to the end as they're the easiest use case of all.
- I've started implementing cases where data provider is a `method call`, so far:
  1. result of the method call is an `Iterable`
  2. result of the method call is an `Iterator`
  3. result of the method call is something else

I created three different methods that deal with these cases. As I told you in the previous comment. The only problem is when the return type is not known. I've been thinking a little bit more about this:
- `Type different` from Iterable and Iterator. That could be ok, we can create a generator out of a value 
- `No type`, two options: 
  1. `Compilation error` throwing something like: **_Method call Custom.getX() returns a value of type "Unknown", it needs to be typed**_
  2. `Wrap whatever it is in a list`: and then create a generator out of that list

I was thinking to create a new feature_branch called `feature/13/iterations_annotation` from `master` and start pushing the code there. Are you ok with this ?

**Comment by Bijnagte** [comment]
Sure I would like to see what you have so far and that seems fine to push the branch there. I also have a partially working implementation that I will push up tonight (U.S. central time) when I am at home. It will be good to compare.
