### ISSUE TITLE
Add ability to control the seed for random generators

### ISSUE THREAD

**Issue by Bijnagte** [Bijnagte/spock-genesis#16]
Open questions are if it should be able to be set per feature or just globally. Globally is easier and it could still have new Random instances per generator so multiple tests would not influence the generation. Using per feature / spec / generator could make it more difficult but would allow some to be reproducible. It may also be beneficial to log out the seed so on fully random runs if there was a failure it could be retried.

**Comment by mariogarcia** [comment]
Normally random number implementation in functional languages use a seed to generate the next random number. That way the generation is deterministic. An example in Haskell could be.

``` haskell
next :: g -> (Int, g)
```
- Haskell reference: https://hackage.haskell.org/package/random-1.1/docs/System-Random.html
- Here's another reference in Scala: http://stackoverflow.com/questions/31818787/pure-functional-random-number-generator-state-monad

Meaning that every time you use the same seed you will end up with the same next random number. 

IMO it should be something accessible through the API. If you want to create a reproducible random generator the use a `Gen.getDouble(seed)` if you don't then use the normal `Gen.getDouble()`.

My two cents
Mario

**Comment by Bijnagte** [comment]
I agree that allowing specific control per generator will be the best. We are already using `java.util.Random` which supports setting the seed. What do is the best way to expose that? Due to using decorators to change the output there may be several Random instances in the pipeline and the outer generator may not have one. We could add a random to the Generator base class that all Generators could access or use a strategy similar to the close method where setSeed is on Generator, is a no-op when not needed and all decorators delegate to the generators that they wrap. I lean towards the single Random on the base class option.

**Comment by mariogarcia** [comment]
Base class option makes sense yes.
