### ISSUE TITLE
Make CyclicGenerator implement InfiniteGenerator?

### ISSUE THREAD

**Issue by drdamour** [Bijnagte/spock-genesis#2]
Is a cyclic generator ever NOT an infinite generator?

**Comment by Bijnagte** [comment]
It is always infinite. Can you describe the use case where you need it to be an infinite generator? Right now InfiniteGenerator and GeneratorDecorator are both abstract classes and CyclicGenerator extends GeneratorDecorator. I would need to add an interface that marks it as infinite (and other infinite generators also) due to the multiple inheritance issue.

**Comment by drdamour** [comment]
I'm doing property testing against some pojo's but instead of getting random iterations back i'm trying to be a bit more explicit and i wanted the generators themselves to define the possible permutations available.

So i send each generator to a warpper around Gen.pojo that finds all the non-infinite generators and realizes them.  It finds the one with the biggest results and replays it (calling `Gen.these( realizedList )` ) for all the others it replays them (the same way) but also `.repeat`'s them so they become infinite.  In this way the biggest finite generator becomes the only finite generator and i have a deterministic number of permutations.

Inifinite loops are my enemy here, until someone solves p=np at least, so i hope the generator rules dont' have any infinite generators that don't claim to be.  I ran into an issue because cyclic fell into this case, simple enough to work around by changing my finite selector logic, but just seemed like something this API could use.

```
static def PojoGenerator pojo(Class target, Map<String, Generator> generators){
        //TODO: Step 1 validate all fields have generators


        //Step 2, determine the biggest finite generator and use that as the limitor by making every other fininte generator infinite via repeat
        def finite = generators
                .findAll {! (it.value instanceof InfiniteGenerator)}
                //for some reason a cycle generator is not considered an infinitegenerator see https://github.com/Bijnagte/spock-genesis/issues/2
                .findAll {! (it.value instanceof CyclicGenerator)}

        if(finite.isEmpty()){
            throw new RuntimeException("must be at least 1 non infinite generator!")
        }

        //realize all non infinite generators so that we can count them and make them replayable
        def realized = finite.collectEntries { [(it.key): it.value.realized] }

        def biggestKey = realized.max { it.value.size }.key

        finite
            //make all but the biggest
            .findAll {!it.key.equals(biggestKey.toString())}
            // replayable, and repeating
            .each {generators.put(it.key, Gen.these(realized.get(it.key)).repeat)}

        //make the biggest replayable
        generators.put(biggestKey.toString(), Gen.these(realized.get(biggestKey)))


        new PojoGenerator(target, new DefinedMapGenerator(generators))
    }
```
