### ISSUE TITLE
Could not find matching constructor for ru.salmond.api.model.Bank (java.util.LinkedHashMap)

### ISSUE THREAD

**Issue by Salmondx** [Bijnagte/spock-genesis#20]
When i try to generate value for java pojo this exception is thrown.
Type has this definition:

``` java
@Data
@Builder
@AllArgsConstructor
public class Bank {
    private String bic;
    private String name;
    private String corrAccount;
    private String city;
}
```

Generator code:

``` java
def bankGenerator() {
        type(Bank,
                bic: string(9, 9),
                name: string,
                corrAccount: string(20, 20),
                city: string
        )
    }
```

As i see, method `next()` has a strange behaviour:

``` java
@Override
    E next() {
        def params = generator.next()
        Class clazz = params.getClass()
        if (hasConstructorFor(clazz)) {
            target.metaClass.invokeConstructor(params)
        } else if (List.isAssignableFrom(clazz)) {
            target.newInstance(*params)
        } else if (Map.isAssignableFrom(clazz)) {
            target.newInstance(params)
        }
    }
```

It compares params class with java.util.Map, but not with target class.

**Comment by Bijnagte** [comment]
Where does `@AllArgsConstructor` come from? I assume it is creating a tuple constructor for the fields in order of declaration. if so then you would need to have your generator produce a tuple not a map: 

``` groovy
def bankGenerator() {
        type(Bank, string(9, 9), string, string(20, 20), string)
    }
```

**Comment by Bijnagte** [comment]
It looks like it is from Lombok: https://projectlombok.org/api/lombok/AllArgsConstructor.html so you will need to call the tuple constructor

**Comment by Bijnagte** [comment]
I confirmed that using a the constructor that takes the arguments in order works. To explain making a new instance with a map: Groovy uses an implicit map constructor. If a class has a no arg constructor then groovy will call it and then call the setters for every property that has a key in the map with the corresponding value.
