### ISSUE TITLE
Gen.value is misleading, Gen.single would be useful

### ISSUE THREAD

**Issue by drdamour** [Bijnagte/spock-genesis#3]
my 2 cents. I expected Gen.value to return a single value, but instead it returns infinite of that value.  seems liek values() might be better, or Gen.infinite()  

I ran into this cause i wanted to do Gen.value(null).then( OtherInfiniteGen) to ensure null was spit out at least once, but obv i spit out infinite nulls.  Gen.these(null) is ambiguous do to signatures...

all just seemed a little messy in my opinion.  Gen.value() or Gen.single() would be helpful i think.  Maybe even a Gen.null().  just my opinions after using it for a few days.

**Comment by Bijnagte** [comment]
I think adding a generator for a single value only once makes sense for chaining things maybe:

``` groovy
Gen.once(null)
```

There are issues with using **null()**  or **getNull()** as a method name as it collides with the **null** keyword

**Comment by drdamour** [comment]
i still think value() is misleading...is that a groovy idiom?
