### ISSUE TITLE
Gen.permute

### ISSUE THREAD

**Issue by drdamour** [Bijnagte/spock-genesis#4]
After playing with this for a while, it works, but it's not giving me exactly what i wanted.  I was hoping for more of a permutation based generator. Say i have
`Gen.pojo(X,  a : Gen.these(1,2), b : Gen.these(3,4))`

realizing this list gives (excuse my json notation) me `[{a : 1, b:3}, {a:2, b:4}]`.   But what i wanted was  `[{a : 1, b:3}, {a : 1, b:4}, {a : 2, b:3}, {a:2, b:4}]`.  this gets more interesting if you use it against a graph, like:

```
Gen.pojo(A,  
  def bGen = Gen.pojo(B,
      b1 : Gen.these(null, 1)
  )

  def bGenInifite = bGen.repeat
  //Non null can just be infinite,  different generator will terminate this
  a1 : Gen.integer, 

  //collections most interesting values are null, empty, 1 item, 2+ items
  a2 : Gen.these(null, [])
    //every permutation of 1 item
    .then bGen.map { [it] }
     //fyi groovy's CrossJoin/pair stuff escapes me at this moment)
    .then bGen.crossJoin( bGen).map( {[it.left, it.right]} )
```

that gives you quite the set of permutations.  Beyond that something like these rules could be built with a reflection factory.  

So kinda a depth first generator off of the rules.

I'm considering putting one together as i have a lot of transformers in my code pipeline that'd i'd be interesting in sending different permutations of my POJO's through just to make sure they don't crash.

It fails to account for relationships between properties. IE Maybe a2 cannot b null if a1 is odd.  Taking it another evolution, you could have a ContextGenerator that get's the currently constructed tree as it moves through the tree, so each generator could decided based upon the current tree.  In that case offering depth and bredth first generators would allow people to construct semantic pojo's for most scenarios.  IE the a1 gen would get an instance of A passed in that already has a2 filled in..or reverse and execute the delegate for the next.

just kinda spitballing here to see if it clicks with anything you've been thinking about.

**Comment by Bijnagte** [comment]
I think having permutations makes sense. this will be a bigger feature so I may cut a release prior to looking into it. A big challenge is understanding how to limit permutations when infinite generators can be in the mix. Adding `isFininite()` helps some but due to turning everything into an Iterator the size is not known. The other consideration may end up being memory constraints if the iterators need to be copied into another structure.

**Comment by drdamour** [comment]
i might suggest skipping infinite generators in the depth.  just pull from them liek you normally would, consider them not part of the permutations but just kinda noise.  If someone wants to force an infinite to trigger some permutations they can always take(n) them to make them finite.

you will have to copy as each finite will need to be replayed for the next iteration.  So fi you have a & b both finite generators, the pattern might be

```
while(a1.hasnext()){
  a = a.next();
  while (b.hasNext()){
     emit(a,b.next())
  }
  b.reset
}
```

maybe instead of reset capturing everything (like repeat does) it can actually restart the rules?

**Comment by Bijnagte** [comment]
@drdamour The recent changes that switched from iterator to iterable will enable this to be done now. I am thinking that it would be available for defined map and tuple generators which would then also make it available for Pojo generation. I was thinking about having a depth limit that would keep infinite generators from trying to traverse there entire depth before moving on.

``` groovy
Gen.tuple(Gen.string(3), Gen.integer).permute(2)
```

would lazily produce something like:

``` groovy
[['abc', 27], ['abc', 42], ['def', 27], ['def', 42]]
```

``` groovy
Gen.map(a: Gen.string(3), b:Gen.integer).permute(2)
```

``` groovy
[[a: 'abc', b: 27], [a: 'abc', b: 42], [a: 'def', b: 27], [a: 'def', b: 42]]
```

without an arg could produce a default max depth, which could be dynamic based on the number of generators

``` groovy
Gen.tuple(Gen.string(3), Gen.integer).permute
```

It is possible that the sizes could be checked and if they are finite then do depth first starting with the smallest generator

**Comment by Bijnagte** [comment]
At this point I am not sure if having a specific permute on the PojoGenerator is even necessary. It could just be the difference between:

``` groovy
Gen.type(Pojo, a: [1, 2], b: [3,4]).permute()
```

and

``` groovy
Gen.type(Pojo, Gen.map(a: [1, 2], b: [3,4]).permute())
```

 thoughts?
I guess the first one reads a little better
cc @mariogarcia
