### ISSUE TITLE
Weird behaviour for invalid generator rule

### ISSUE THREAD

**Issue by drdamour** [Bijnagte/spock-genesis#7]
~~I had a pojo (in java) that was relying on the implciit default constructor being used.  When i used PojoGenerator to create this it made groovy_proxy objects instead of my Pojo's, and none of my fields were populated with values.  I'm thinking this is a bug.~~

~~Adding an explicit default constructor resolved then issue.~~
(redacted see later comments for actual cause)

**Comment by Bijnagte** [comment]
Did the pojo have other declared constructors?

**Comment by drdamour** [comment]
no

**Comment by Bijnagte** [comment]
could you supply a minimum failing test case?

**Comment by drdamour** [comment]
maybe later.  it also happens if the genrator rule is type mismathed.  IE gen.string for an int

**Comment by drdamour** [comment]
k cornered it, i get a groovy proxy when i have a generator rule for a field that does't work.  IE bad name or bad type.

**Comment by drdamour** [comment]
```
    public static class pojo {
        String a;

        public String getA() {
            return a;
        }

        public void setA(String a) {
            this.a = a;
        }
    }

    @Test
    public void testPojoGen(){
        HashMap<String,Object> generators = new HashMap<String, Object>();
        generators.put("a", Gen.getString());
        generators.put("NOT-a", Gen.getString());

        pojo i = (pojo)Gen.type(generators, pojo.class).next();
        assertNotNull(i.getA());
    }
```
